// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Yunus Emre Alpu",
            "url": "https://yunusemrealpu.netlify.app",
            "email": "YunusAlpu@icloud.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shift-schedule/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "update a shift schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "update a shift schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shift Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "update shift schedule",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.updateShiftScheduleDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully updated shift schedule",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot update shift schedule due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot update shift schedule due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot update shift schedule due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        },
        "/shift-schedules": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get all shift schedules with pagination, search, sort and filter options",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "get all shift schedules with filters",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 10,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search in alias, description, organization, manager",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "created_at",
                        "description": "Sort by field (alias, year, start_date, end_date, status, organization_name, manager_name)",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "DESC",
                        "description": "Sort order (ASC or DESC)",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter only active records (not deleted)",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by status (0:pending, 1:approved, 2:rejected)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by year",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by start date (YYYY-MM-DD)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by end date (YYYY-MM-DD)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by organization name",
                        "name": "organization_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by organization mail",
                        "name": "organization_mail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by organization phone",
                        "name": "organization_phone",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by manager name",
                        "name": "manager_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by manager mail",
                        "name": "manager_mail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by manager phone",
                        "name": "manager_phone",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user name",
                        "name": "user_name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user mail",
                        "name": "user_mail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user phone",
                        "name": "user_phone",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by shift ID",
                        "name": "shift_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by shift start (YYYY-MM-DD HH:MM:SS)",
                        "name": "shift_start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by shift end (YYYY-MM-DD HH:MM:SS)",
                        "name": "shift_end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by shift user",
                        "name": "shift_user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get all shift schedules successfully",
                        "schema": {
                            "$ref": "#/definitions/models.ShiftScheduleListResponse"
                        }
                    },
                    "400": {
                        "description": "cannot get all shift schedules due to invalid request parameters",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot get all shift schedules due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "create a new shift schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "create a new shift schedule",
                "parameters": [
                    {
                        "description": "Alias",
                        "name": "alias",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Description",
                        "name": "description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Frequency",
                        "name": "frequency",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Start Date",
                        "name": "start_date",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "End Date",
                        "name": "end_date",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Year",
                        "name": "year",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Status",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Organization",
                        "name": "organization",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    },
                    {
                        "description": "Manager",
                        "name": "manager",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    },
                    {
                        "description": "Users",
                        "name": "users",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    },
                    {
                        "description": "Shifts",
                        "name": "shifts",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully created shift schedule",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot create shift schedule due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot create shift schedule due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot create shift schedule due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        },
        "/shift-schedules/deleted": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get all deleted shift schedules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "get all deleted shift schedules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shift Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get all shift schedules successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot get only deleted shift schedules due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot get only deleted shift schedules due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot get only deleted shift schedules due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        },
        "/shift-schedules/id": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get a shift schedule by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "get a shift schedule by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shift Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get shift by id successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot get shift schedule by id due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot get shift schedule by id due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot get shift schedule by id due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        },
        "/shift-schedules/week": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get shift schedules by current week",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "get shift schedules by current week",
                "responses": {
                    "200": {
                        "description": "get shifts by current week successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot get shifts schedule by current week due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot get shifts schedule by current week due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot get shifts schedule by current week due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        },
        "/shift-schedules/week/paginated": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get shift schedules by week with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "get shift schedules by current week with pagination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "asc",
                            "desc"
                        ],
                        "type": "string",
                        "description": "orderBy",
                        "name": "orderBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get shifts by current week successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot get shifts schedule by current week due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot get shifts schedule by current week due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot get shifts schedule by current week due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        },
        "/shift-schedules/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "delete a shift schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "delete a shift schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shift Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully deleted shift schedule",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot delete shift schedule due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot delete shift schedule due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot delete shift schedule due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        },
        "/shift-schedules/{id}/restore": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "restored a shift schedule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "restore a shift schedule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shift Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successfully restored shift schedule",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot restore shift schedule due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot restore shift schedule due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot restore shift schedule due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        },
        "/shift-schedules/{year}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "get a shift schedules by year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shift"
                ],
                "summary": "get a shift schedules by year",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shift Schedule Year",
                        "name": "year",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "get shifts by year successfully",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "400": {
                        "description": "cannot get shifts schedule by year due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "422": {
                        "description": "cannot get shifts schedule by year due to invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    },
                    "500": {
                        "description": "cannot get shifts schedule by year due to internal server error",
                        "schema": {
                            "$ref": "#/definitions/handlers.RespondJson"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.RespondJson": {
            "type": "object",
            "properties": {
                "intent": {
                    "type": "string"
                },
                "message": {},
                "status": {
                    "type": "boolean"
                }
            }
        },
        "handlers.updateShiftScheduleDTO": {
            "type": "object",
            "required": [
                "alias",
                "description",
                "end_date",
                "frequency",
                "manager",
                "organization",
                "shifts",
                "start_date",
                "users",
                "year"
            ],
            "properties": {
                "alias": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "frequency": {
                    "description": "1, 2, 3, 4, 5, 6, 7 (days of the week)",
                    "type": "integer"
                },
                "manager": {
                    "type": "array",
                    "items": {}
                },
                "organization": {
                    "type": "array",
                    "items": {}
                },
                "shifts": {
                    "type": "array",
                    "items": {}
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "description": "0: pending, 1: approved, 2: rejected",
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {}
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "models.ShiftSchedule": {
            "type": "object",
            "properties": {
                "CreatedAt": {
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                },
                "UpdatedAt": {
                    "type": "string"
                },
                "alias": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "frequency": {
                    "description": "1, 2, 3, 4, 5, 6, 7 (days of the week)",
                    "type": "integer"
                },
                "manager": {
                    "type": "array",
                    "items": {}
                },
                "organization": {
                    "type": "array",
                    "items": {}
                },
                "shifts": {
                    "type": "array",
                    "items": {}
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "description": "0: pending, 1: approved, 2: rejected",
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {}
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "models.ShiftScheduleListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ShiftSchedule"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "sort_by": {
                    "type": "string"
                },
                "sort_order": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/shyft",
	Schemes:          []string{"http", "https"},
	Title:            "Shift Scheduler Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
